config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show.html.erb", as: :rails_health_check
  root to: "home#index"
  resources :genres, only: [:index, :show, :new, :create, :edit, :update]
  resources :directors, only: [:index, :show, :new, :create, :edit, :update]
  resources :movies, only: [:show, :new, :create, :edit, :update] do
    patch :publish, :turn_draft, on: :member
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :genre
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :directors
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  enum release_status: { not_released: 0, released: 1 }
  enum draft_status: { draft: 0, published: 1 }

  belongs_to :director
  belongs_to :genre

  has_one_attached :poster

  def small_poster
    self.poster.variant(resize_to_limit: [300, 300]) if self.poster.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
    @movies_from_director = Movie.where(director: @director.id)
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(params.require(:director)
      .permit(:name, :nationality, :birth_date, :genre_id))

    return redirect_to director_path(@director.id) if @director.save
    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    return redirect_to director_path(params[:id]) if
      Director.find(params[:id])
        .update(params.require(:director)
        .permit(:name, :nationality, :birth_date, :genre_id))

    render :edit
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @movies_from_genre = Movie.where(genre_id: @genre.id)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(params.require(:genre).permit(:name))

    return redirect_to genre_path(@genre.id) if @genre.save
    render :new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    return redirect_to genre_path(params[:id]) if
      Genre.find(params[:id]).update(params.require(:genre).permit(:name))

    render :edit
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @released_movies = Movie.published.released
    @not_released_movies = Movie.published.not_released
  end
end

app/controllers/movies_controller.rb
  class MoviesController < ApplicationController
    def show
      @movie = Movie.find(params[:id])
    end

    def new
      @movie = Movie.new
    end

    def create
      @movie = Movie.new(params.require(:movie).permit(
        :title,
        :release_year,
        :synopsis,
        :country,
        :duration,
        :poster,
        :director_id,
        :genre_id,
        :release_status,
        :draft_status))

      return redirect_to movie_path(@movie.id) if @movie.save
      render :new
    end

    def edit
      @movie = Movie.find(params[:id])
    end

    def update
      return redirect_to movie_path(params[:id]) if
       Movie.find(params[:id]).update(params.require(:movie).permit(
         :title,
         :release_year,
         :synopsis,
         :country,
         :duration,
         :poster,
         :director_id,
         :genre_id,
         :release_status,
         :draft_status))

      render :edit
    end

    def publish
      movie = Movie.find(params[:id])
      movie.published!
      redirect_to movie_path(movie.id)
    end

    def turn_draft
      movie = Movie.find(params[:id])
      movie.draft!
      redirect_to movie_path(movie.id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<%= form_with model: director do |form| %>
  <%= form.label 'Nome: ' %>
  <%= form.text_field :name %>
  <%= form.label 'Nacionalidade: ' %>
  <%= form.text_field :nationality %>
  <%= form.label 'Data de Nascimento: ' %>
  <%= form.date_select :birth_date, start_year: 1900, end_year: Time.now.year %>
  <%= form.label 'Gênero Preferido: ' %>
  <%= form.collection_select :genre_id, Genre.order(:name), :id, :name %>
  <%= form.submit 'Salvar' %>
<% end %>

app/views/directors/edit.html.erb
<h1>Editar Diretor</h1>
<%= render partial: 'form', locals: { director: @director } %>

app/views/directors/index.html.erb
<h1>Lista de Diretores</h1>
<ul>
  <% @directors.each do |director| %>
    <li><%= link_to director.name, director_path(director) %></li>
  <% end %>
</ul>

app/views/directors/new.html.erb
<h1>Adicionar Diretor</h1>
<%= render partial: 'form', locals: { director: @director } %>

app/views/directors/show.html.erb
<main>
  <h1>Diretor <%= @director.name %></h1>
  <ul>
    <li>Nacionalidade: <%= @director.nationality %></li>
    <li>Data de Nascimento: <%= @director.birth_date.strftime('%d/%m/%Y') %></li>
    <li>Gênero Preferido: <%= @director.genre.name %></li>
  </ul>
  <%= link_to 'Alterar Dados do Diretor', edit_director_path %>
  <h2>Filmes Dirigidos</h2>
  <ul>
    <% @movies_from_director.each do |movie| %>
      <li><%= link_to "#{movie.title} (#{movie.release_year})", movie_path(movie) %></li>
    <% end %>
  </ul>
</main>

app/views/genres/_form.html.erb
<%= form_with model: @genre do |form| %>
  <%= form.label 'Nome: ' %>
  <%= form.text_field :name %>
  <%= form.submit 'Salvar' %>
<% end %>

app/views/genres/edit.html.erb
<h1>Editar Gênero</h1>
<%= render partial: 'form', locals: { genre: @genre } %>

app/views/genres/index.html.erb
<h1>Lista de Gêneros</h1>
<ul>
  <% @genres.each do |genre| %>
    <li><%= link_to genre.name, genre_path(genre) %></li>
  <% end %>
</ul>

app/views/genres/new.html.erb
<h1>Adicionar Gênero</h1>
<%= render partial: 'form', locals: { genre: @genre } %>

app/views/genres/show.html.erb
<main>
  <h1>Gênero <%= @genre.name %></h1>
  <%= link_to 'Alterar Nome do Gênero', edit_genre_path %>
  <h2>Filmes do Gênero <%= @genre.name %></h2>
  <ul>
    <% @movies_from_genre.each do |movie| %>
      <li><%= link_to "#{movie.title} (#{movie.release_year})", movie_path(movie) %></li>
    <% end %>
  </ul>
</main>

app/views/home/index.html.erb
<main>
  <h1>Catálogo de Filmes</h1>
  <h2>Filmes Lançados</h2>
  <ul>
    <% @released_movies.each do |movie| %>
      <li>
        <%= link_to "#{movie.title} (#{movie.release_year})", movie_path(movie) %>
        <br>
        <%= image_tag(movie.small_poster) %>>
      </li>
    <% end %>
  </ul>
  <h2>Filmes Não Lançados</h2>
  <ul>
    <% @not_released_movies.each do |movie| %>
      <li>
        <%= link_to "#{movie.title} (#{movie.release_year})", movie_path(movie) %>
        <br>
        <%= image_tag(movie.small_poster) %>>
      </li>
    <% end %>
  </ul>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>MovieCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <menu>
      <ul>
        <li><%= link_to 'Página Inicial', root_path %></li>
        <li><%= link_to 'Adicionar Filme', new_movie_path %></li>
        <li><%= link_to 'Listar Gêneros', genres_path %></li>
        <li><%= link_to 'Adicionar Gênero', new_genre_path %></li>
        <li><%= link_to 'Listar Diretores', directors_path %></li>
        <li><%= link_to 'Adicionar Diretor', new_director_path %></li>
      </ul>
    </menu>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie do |form| %>
  <%= form.label 'Título: ' %>
  <%= form.text_field :title %>

  <%= form.label 'Ano de Lançamento: ' %>
  <%= form.select :release_year, 1888..Date.current.year %>

  <%= form.label 'Lançado: ' %>
  <%= form.check_box :release_status, {}, "released", "not_released" %>

  <%= form.label 'Sinopse: ' %>
  <%= form.text_area :synopsis %>

  <%= form.label 'País de Origem: ' %>
  <%= form.text_field :country %>

  <%= form.label 'Duração: ' %>
  <%= form.number_field :duration %>

  <%= form.label 'Diretor: ' %>
  <%= form.collection_select :director_id, Director.order(:name), :id, :name %>

  <%= form.label 'Gênero: ' %>
  <%= form.collection_select :genre_id, Genre.order(:name), :id, :name %>

  <%= form.label 'Poster do Filme: ' %>
  <%= form.file_field :poster %>

  <%= form.label 'Rascunho: ' %>
  <%= form.check_box :draft_status, {}, "draft", "published" %>

  <%= form.submit 'Salvar' %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editar Filme</h1>
<%= render partial: 'form', locals: { movie: @movie } %>

app/views/movies/new.html.erb
<h1>Adicionar Diretor</h1>
<%= render partial: 'form', locals: { movie: @movie } %>

app/views/movies/show.html.erb
<main>
  <h1>Informações Sobre o Filme</h1>

  <ul>
    <li><%= image_tag(@movie.small_poster) %></li>
    <li>Título: <%= @movie.title %></li>
    <li>Ano de Lançamento: <%= @movie.release_year %></li>
    <li>Lançado: <%= @movie.released? ? 'Sim' : 'Não'%></li>
    <li>Sinopse: <%= @movie.synopsis %></li>
    <li>País de Origem: <%= @movie.country %></li>
    <li>Duração: <%= @movie.duration %> minutos</li>
    <li>Diretor: <%= @movie.director.name %></li>
    <li>Gênero: <%= @movie.genre.name %></li>
  </ul>
  <%= link_to 'Editar', edit_movie_path %>
  <% if @movie.draft? %>
    <%= button_to 'Publicar', publish_movie_path, { method: 'patch' } %>
  <% else %>
    <%= button_to 'Transformar em Rascunho', turn_draft_movie_path, { method: 'patch' } %>
  <% end %>
</main>